// Registry and resolver for all 102 card artworks and race portraits

export const CARD_IMAGES: Record<string, string> = {
  // Portraits (10 Rassen)
  demon_portrait: './cards/demon_portrait.png',
  dragon_portrait: './cards/dragon_portrait.png',
  dwarf_portrait: './cards/dwarf_portrait.png',
  elf_portrait: './cards/elf_portrait.png',
  fairy_portrait: './cards/fairy_portrait.png',
  human_portrait: './cards/human_portrait.png',
  orc_portrait: './cards/orc_portrait.png',
  undead_portrait: './cards/undead_portrait.png',
  vampire_portrait: './cards/vampire_portrait.png',
  werewolf_portrait: './cards/werewolf_portrait.png',

  // Spells
  acid_rain: './cards/acid_rain.png',
  apocalypse: './cards/apocalypse.png',
  arcane_bolt: './cards/arcane_bolt.png',
  arrow_salvo: './cards/arrow_salvo.png',
  bite: './cards/bite.png',
  black_hole: './cards/black_hole.png',
  blood_coin: './cards/blood_coin.png',
  blood_rage: './cards/blood_rage.png',
  chain_lightning: './cards/chain_lightning.png',
  dark_bolt: './cards/dark_bolt.png',
  death_blow: './cards/death_blow.png',
  divine_blessing: './cards/divine_blessing.png',
  dragon_claw: './cards/dragon_claw.png',
  dragon_hoard: './cards/dragon_hoard.png',
  elixir: './cards/elixir.png',
  emergency_heal: './cards/emergency_heal.png',
  execute: './cards/execute.png',
  fairy_bolt: './cards/fairy_bolt.png',
  fairy_dust: './cards/fairy_dust.png',
  fireball: './cards/fireball.png',
  flame_storm: './cards/flame_storm.png',
  hammer_throw: './cards/hammer_throw.png',
  hellfire: './cards/hellfire.png',
  howl: './cards/howl.png',
  knife_throw: './cards/knife_throw.png',
  major_heal: './cards/major_heal.png',
  meditation: './cards/meditation.png',
  meteor: './cards/meteor.png',
  plunder: './cards/plunder.png',
  poison_spit: './cards/poison_spit.png',
  shockwave: './cards/shockwave.png',
  slash: './cards/slash.png',
  smoke_bomb: './cards/smoke_bomb.png',
  soul_harvest: './cards/soul_harvest.png',
  soul_sever: './cards/soul_sever.png',
  soul_steal: './cards/soul_steal.png',
  stone_strike: './cards/stone_strike.png',
  summon_skeleton: './cards/summon_skeleton.png',
  time_warp: './cards/time_warp.png',
  timestop: './cards/timestop.png',
  vampire_bite: './cards/vampire_bite.png',
  weak_strike: './cards/weak_strike.png',

  // Units
  angel: './cards/angel.png',
  archer: './cards/archer.png',
  assassin: './cards/assassin.png',
  barracks: './cards/barracks.png',
  berserker: './cards/berserker.png',
  demon_lord: './cards/demon_lord.png',
  dragon: './cards/dragon.png',
  guard_dog: './cards/guard_dog.png',
  healer: './cards/healer.png',
  knight: './cards/knight.png',
  militia: './cards/militia.png',
  necromancer: './cards/necromancer.png',
  peasant: './cards/peasant.png',
  shield_bearer: './cards/shield_bearer.png',
  titan: './cards/titan.png',
  war_machine: './cards/war_machine.png',

  // Buildings
  alchemy_lab: './cards/alchemy_lab.png',
  barricade: './cards/barricade.png',
  blood_altar: './cards/blood_altar.png',
  catapult: './cards/catapult.png',
  cathedral: './cards/cathedral.png',
  crypt: './cards/crypt.png',
  demon_gate: './cards/demon_gate.png',
  den: './cards/den.png',
  dragon_nest: './cards/dragon_nest.png',
  fairy_ring: './cards/fairy_ring.png',
  forge: './cards/forge.png',
  fortress: './cards/fortress.png',
  gold_mine: './cards/gold_mine.png',
  graveyard: './cards/graveyard.png',
  mage_tower: './cards/mage_tower.png',
  marketplace: './cards/marketplace.png',
  recruit_tent: './cards/recruit_tent.png',
  stone_wall: './cards/stone_wall.png',
  temple: './cards/temple.png',
  treasure_chest: './cards/treasure_chest.png',
  vault: './cards/vault.png',
  watch_tower: './cards/watch_tower.png',
  wooden_wall: './cards/wooden_wall.png',

  // Resources
  coin: './cards/coin.png',
  coin_pouch: './cards/coin_pouch.png',
  gold_scale: './cards/gold_scale.png',
  herb_potion: './cards/herb_potion.png',
  knowledge_book: './cards/knowledge_book.png',
  mana_crystal: './cards/mana_crystal.png',
  ore_chunk: './cards/ore_chunk.png',
  treasure_hoard: './cards/treasure_hoard.png',
  war_horn: './cards/war_horn.png',
  whetstone: './cards/whetstone.png',
  wisdom_scroll: './cards/wisdom_scroll.png'
};

export function getCardImagePath(id: string): string {
  return CARD_IMAGES[id] ?? './cards/weak_strike.png';
}
